---
- name: TASK MENGINSTAL DAN MENJALANKAN NGINX
  hosts: localhost
  become: true

  tasks:
     - name: SEDANG MENGINSTALL NGINX . . . .
       apt:
          name: ['nginx']
          state: latest

     - name: MEMULAI NGINX . . . .
       service:
          name: nginx
          state: started
          enabled: yes
     
     - name: MENGIRIM NOTIFIKASI KE TELEGRAM . . . .
       telegram:
          token: '5213394966:AAFZf2AOeZidn03HwoociE0vMxFdsiT9thI'
          api_args:
            chat_id: 998661892
            parse_mode: "markdown"
            msg: AUTOMATISASI BERHASIL . . . . . .
            disable_notification: True

  handlers:
      - name: RESTART NGINX
        service:
          become: yes
          name: nginx
          state: restarted
