---
- name: TASK MENGINSTAL DAN MENJALANKAN NGINX
  hosts: localhost
  become: true

  tasks:
     - name: SEDANG MENGINSTALL NGINX . . . .
       apt:
          name: ['nginx']
          state: latest

     - name: MEMULAI NGINX . . . .
       service:
          name: nginx
          state: started
          enabled: yes

  handlers:
      - name: RESTART NGINX
        service:
          become: yes
          name: nginx
          state: restarted
